# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YLSinaBlogNew' do

pod 'AFNetworking', '~> 2.6.3'
 pod 'Masonry', '~> 0.6.3'
pod 'SVProgressHUD', '~> 2.0-beta'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 3.0.7'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'


end

